# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout tagged_ptr
        uses: actions/checkout@v2.3.4

      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount bazel cache
        uses: actions/cache@v2.1.6
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      # Runs a single command using the runners shell
      - name: Run tests
        run: |
          bazelisk test --build_tests_only //...
